// <auto-generated />
namespace Furniture_Rental_APP_ASP.NET_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApplyAnnotationsToClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplyAnnotationsToClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201912191658038_ApplyAnnotationsToClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
